//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hxgDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public long US_ID { get; set; }
        public string US_LOGNAME { get; set; }
        public string US_PASSWORD { get; set; }
        public string US_NICKNAME { get; set; }
        public string US_TYPE { get; set; }
        public int US_AGE { get; set; }
        public string US_GENDER { get; set; }
        public string US_LOGO { get; set; }
        public Nullable<long> US_SCORE { get; set; }
        public string US_PARENTSPSWD { get; set; }
        public int ISACTIVE { get; set; }
        public System.DateTime CREATETIME { get; set; }
        public System.DateTime LASTUPDATETIME { get; set; }
    }
}
